---
# tasks file for ansible-role-epel

- name: Validating if supported platform
  fail: 
    msg: EPEL is only supported on RedHat compatible OS
  when: ansible_os_family != 'RedHat'

- name: Enable EPEL repository on RHEL compatible OS
  dnf:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
    update_cache: yes
  when: ansible_distribution_major_version == '8'

- name: Enable EPEL repository on RHEL compatible OS
  yum:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
    update_cache: yes
  when: ansible_distribution_major_version == '7'